### ISSUE TITLE
 翻訳で -A が消失

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-uwp.ja-jp#102]
Moved from: https://github.com/MicrosoftDocs/windows-uwp/issues/2115
@ufcpp commented yesterday — with docs.microsoft.com
翻訳で -A Api の A が消えてる。おそらく不定冠詞扱いされている。

⚠ このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。

    ID: 8a28119a-77f2-160c-a4f1-f90ef9153423
    Version Independent ID: 28b24e82-f0ef-cceb-2136-f8dbfabfcadc
    Content: Windows UTF-8 コードページを使用する - UWP apps
    Content Source: windows-apps-src/design/globalizing/use-utf8-code-page.md
    Product: uwp
    Technology: design
    GitHub Login: @Karl-Bridge-Microsoft
    Microsoft Alias: kbridge

@nokura commented 21 hours ago
@DavidPrio please move this feedback to Japanese repo and fix it. We have to restore "A" in -A, which might be removed as it is mistakenly regarded as Indefinite article.

Current: "Unicode"-W のバリエーションを Api 経由で強調してきました。
Change to: "Unicode"-W のバリエーションを -A Api 経由で強調してきました。

Current: Api は UTF-8 で動作します。
Change to: -A Api は UTF-8 で動作します。

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@ufcpp

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/windows/uwp/design/globalizing/use-utf8-code-page

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
