### ISSUE TITLE
[LOC] Back-Translation "bingmaps: ms でドライブを: および ms のウォーク-に。" → "bingmaps:, ms-drive-to:, and ms-walk-to:"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-uwp.ja-jp#12]
@hyoshioka0128 commented on [Tue May 07 2019](https://github.com/MicrosoftDocs/windows-uwp/issues/1659)

https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-default-app

_Adding these lines from different Issues to work them together since they belong to the same page and were logged by the same contributor:_

Back-Translation "ms yellowpage: でしょうか入力 =[キーワード]& メソッド =[文字列または T9。]" → " #1658	(from https://github.com/MicrosoftDocs/windows-uwp/issues/1658)
Typo "ms yellowpage:" → "ms-yellowpage:" (from https://github.com/MicrosoftDocs/windows-uwp/issues/1652)
Typo "ms tonepicker:" → "ms-tonepicker:" (from https://github.com/MicrosoftDocs/windows-uwp/issues/1651)
 Back-Translation "ms ストア。" → "ms-store:" (from https://github.com/MicrosoftDocs/windows-uwp/issues/1649)
Back-Translation "ms 写真:" → "ms-photos:" (from https://github.com/MicrosoftDocs/windows-uwp/issues/1648)
Back-Translation "ms ユーザー:	"" → ""ms-people:""(from	https://github.com/MicrosoftDocs/windows-uwp/issues/1647)
Back-Translation "ms チャット:" → "ms-chat:" #1646	(from https://github.com/MicrosoftDocs/windows-uwp/issues/1646)
Back-Translation "ms 呼び出し。" → "ms-call:" #1645	(from https://github.com/MicrosoftDocs/windows-uwp/issues/1645)
Back-Translation "ms-設定:" → "ms-settings:" #1644	(from https://github.com/MicrosoftDocs/windows-uwp/issues/1644)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ae2608d3-38b8-2404-d138-1ba17772e72c
* Version Independent ID: 535d38b3-3174-fc77-ec58-7b5732ba803c
* Content: [URI に応じた既定のアプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-default-app)
* Content Source: [windows-apps-src/launch-resume/launch-default-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-default-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
