### ISSUE TITLE
[LOC] Back-Translation "メール" → "Email"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-uwp.ja-jp#13]
@hyoshioka0128 commented on [Sat May 18 2019](https://github.com/MicrosoftDocs/windows-uwp/issues/1686)

https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-people-apps
_Adding these lines from different Issues to work them together since they belong to the same page and were logged by the same contributor:_

[LOC] Back-Translation "ms ユーザー: " → "ms-people: (from https://github.com/MicrosoftDocs/windows-uwp/issues/1650)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a1d62e94-aa32-467f-fa2d-14e630543e1f
* Version Independent ID: 2ab8ae17-c66e-3bd8-2a28-a8804a06a66a
* Content: [People アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-people-apps)
* Content Source: [windows-apps-src/launch-resume/launch-people-apps.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-people-apps.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @<contributor's GITHUB name>,

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review https://github.com/MicrosoftDocs/windows-uwp/issues/1686. For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
