### ISSUE TITLE
Back-Translation "ms-設定:" → "ms-settings:"

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/windows-uwp.ja-jp#8]
@hyoshioka0128 commented on [Mon May 06 2019](https://github.com/MicrosoftDocs/windows-uwp/issues/1639)

https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-settings-app

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 987ec16c-9456-93a4-177a-dbd563be7eb7
* Version Independent ID: f41f0344-f7f6-f092-a6bf-fc4184a9b460
* Content: [Windows 設定アプリの起動 - Windows UWP applications](https://docs.microsoft.com/ja-jp/windows/uwp/launch-resume/launch-settings-app)
* Content Source: [windows-apps-src/launch-resume/launch-settings-app.md](https://github.com/MicrosoftDocs/windows-uwp-pr.ja-jp/blob/live-sxs/windows-apps-src/launch-resume/launch-settings-app.md)
* Product: **uwp**
* Technology: **processes-and-threading**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by CeciAc** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
